### ISSUE TITLE
Design Document (GRASP) for sequence diagrams  

### ISSUE THREAD

**Issue by suphaphan** [suphaphan/CSC440TopDollarDeals#6]
Design Document
The design document contains design-level sequence diagrams and design class diagrams describing all of the classes and major interactions to be implemented in this iteration. In this iteration, the team must add a 1-2 page writeup explaining the reasons for designing each diagram. The explanation must include which GRASP patterns are used and why.

**Comment by wilsra01** [comment]
GRASP explanation included after Class Diagrams
